@OwlMapper.Bootstrapper_HostAddress = http://localhost:5068

### Get Application Info
GET {{OwlMapper.Bootstrapper_HostAddress}}/
Accept: application/json

###

### Get Health Status
GET {{OwlMapper.Bootstrapper_HostAddress}}/health
Accept: application/json

###

### Get Example Module Info
GET {{OwlMapper.Bootstrapper_HostAddress}}/example
Accept: application/json

###
