@OwlMapper.Bootstrapper_HostAddress = https://localhost:2137

# Get application information
GET {{OwlMapper.Bootstrapper_HostAddress}}/
Accept: application/json

###

# Check application health
GET {{OwlMapper.Bootstrapper_HostAddress}}/health
Accept: application/json

###
