name: Build and Test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 10 SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.102'

      - name: Cache NuGet packages
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Directory.Packages.props') }}

      - name: Restore Bootstrapper
        run: dotnet restore ./src/Bootstrapper/Bootstrapper.csproj

      - name: Build Bootstrapper
        run: dotnet build --configuration Release --no-restore ./src/Bootstrapper/Bootstrapper.csproj

      - name: Check Format
        run: dotnet format --verify-no-changes --verbosity diagnostic

      - name: Install NUnit Runner
        if: success()
        shell: cmd
        run:
          nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory .

      - name: Run Unit Tests
        shell: bash
        run: |
          mapfile TEST_PROJECTS < <(find . -name "*.UnitTests.*.csproj")
          if [ ${#TEST_PROJECTS[@]} -eq 0 ]; then
            echo "No unit test projects found - skipping tests."
            exit 0
          fi

          for proj in "${TEST_PROJECTS[@]}"; do
            echo "Running unit tests: $proj"
            dotnet test "$proj" -c Release
          done